language: python
python:
  - 2.7.9
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
script:
  - flake8 . --exclude=__init__.py --exclude=run.py --max-line-length=120
  - python -m unittest discover -s tests/ -p '*_test.py'
  - coverage run --source=src setup.py test
after_success:
  - coveralls
deploy:
  provider: heroku
  app: irolink-app
  api_key: $HEROKU_API_KEY
  on:
    repo: irolink/irolink-app
notifications:
  email:
    recipients: project.irolink@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
