language: python
python:
  - 2.7.9
before_script:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s tests/ -p '*_test.py'
deploy:
  provider: heroku
  app: irolink-app
  api_key: $HEROKU_API_KEY
  on:
    repo: irolink/irolink-app
notifications:
  email:
    recipients: project.irolink@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
