# -*- coding: utf-8 -*-
HTML16COLORS = [
    ['White',   'ffffff'],
    ['Silver',  'c0c0c0'],
    ['Gray',    '808080'],
    ['Black',   '000000'],
    ['Red',     'ff0000'],
    ['Maroon',  '800000'],
    ['Yellow',  'ffff00'],
    ['Olive',   '808000'],
    ['Lime',    '00ff00'],
    ['Green',   '008000'],
    ['Aqua',    '00ffff'],
    ['Teal',    '008080'],
    ['Blue',    '0000ff'],
    ['Navy',    '000080'],
    ['Fuchsia', 'ff00ff'],
    ['Purple',  '800080']
]

X11COLORS = [
    ['Indian Red',              'cd5c5c'],
    ['Light Coral',             'f08080'],
    ['Salmon',                  'fa8072'],
    ['Dark Salmon',             'e9967a'],
    ['Light Salmon',            'ffa07a'],
    ['Crimson',                 'dc143c'],
    ['Red',                     'ff0000'],
    ['Fire Brick',              'b22222'],
    ['Dark Red',                '8b0000'],
    ['Pink',                    'ffc0cb'],
    ['Light Pink',              'ffb6c1'],
    ['Hot Pink',                'ff69b4'],
    ['Deep Pink',               'ff1493'],
    ['Medium Violet Red',       'c71585'],
    ['Pale Violet Red',         'db7093'],
    ['Light Salmon',            'ffa07a'],
    ['Coral',                   'ff7f50'],
    ['Tomato',                  'ff6347'],
    ['Orange Red',              'ff4500'],
    ['Dark Orange',             'ff8c00'],
    ['Orange',                  'ffa500'],
    ['Gold',                    'ffd700'],
    ['Yellow',                  'ffff00'],
    ['Light Yellow',            'ffffe0'],
    ['Lemon Chiffon',           'fffacd'],
    ['Light Goldenrod Yellow',  'fafad2'],
    ['Papaya Whip',             'ffefd5'],
    ['Moccasin',                'ffe4b5'],
    ['Peach Puff',              'ffdab9'],
    ['Pale Goldenrod',          'eee8aa'],
    ['Khaki',                   'f0e68c'],
    ['Dark Khaki',              'bdb76b'],
    ['Lavender',                'e6e6fa'],
    ['Thistle',                 'd8bfd8'],
    ['Plum',                    'dda0dd'],
    ['Violet',                  'ee82ee'],
    ['Orchid',                  'da70d6'],
    ['Fuchsia',                 'ff00ff'],
    ['Magenta',                 'ff00ff'],
    ['Medium Orchid',           'ba55d3'],
    ['Medium Purple',           '9370db'],
    ['Amethyst',                '9966cc'],
    ['Blue Violet',             '8a2be2'],
    ['Dark Violet',             '9400d3'],
    ['Dark Orchid',             '9932cc'],
    ['Dark Magenta',            '8b008b'],
    ['Purple',                  '800080'],
    ['Indigo',                  '4b0082'],
    ['Slate Blue',              '6a5acd'],
    ['Dark Slate Blue',         '483d8b'],
    ['Medium Slate Blue',       '7b68ee'],
    ['Green Yellow',            'adff2f'],
    ['Chartreuse',              '7fff00'],
    ['Lawn Green',              '7cfc00'],
    ['Lime',                    '00ff00'],
    ['Lime Green',              '32cd32'],
    ['Pale Green',              '98fb98'],
    ['Light Green',             '90ee90'],
    ['Medium Spring Green',     '00fa9a'],
    ['Spring Green',            '00ff7f'],
    ['Medium Sea Green',    '3CB371'],
    ['Sea Green',           '2E8B57'],
    ['Forest Green',        '228B22'],
    ['Green',               '008000'],
    ['Dark Green',          '006400'],
    ['Yellow Green', '9ACD32'],
    ['Olive Drab', '6B8E23'],
    ['Olive', '808000'],
    ['Dark Olive Green', '556B2F'],
    ['Medium Aquamarine', '66CDAA'],
    ['Dark Sea Green', '8FBC8F'],
    ['Light Sea Green', '20B2AA'],
    ['Dark Cyan', '008B8B'],
    ['Teal', '008080'],
    ['Aqua', '00FFFF'],
    ['Cyan', '00FFFF'],
    ['Light Cyan', 'E0FFFF'],
    ['Pale Turquoise', 'AFEEEE'],
    ['Aquamarine', '7FFFD4'],
    ['Turquoise', '40E0D0'],
    ['Medium Turquoise', '48D1CC'],
    ['Dark Turquoise', '00CED1'],
    ['Cadet Blue', '5F9EA0'],
    ['Steel Blue', '4682B4'],
    ['Light Steel Blue', 'B0C4DE'],
    ['Powder Blue', 'B0E0E6'],
    ['Light Blue', 'ADD8E6'],
    ['Sky Blue', '87CEEB'],
    ['Light Sky Blue', '87CEFA'],
    ['Deep Sky Blue', '00BFFF'],
    ['Dodger Blue', '1E90FF'],
    ['Cornflower Blue', '6495ED'],
    ['Medium Slate Blue', '7B68EE'],
    ['Royal Blue', '4169E1'],
    ['Blue', '0000FF'],
    ['Medium Blue', '0000CD'],
    ['Dark Blue', '00008B'],
    ['Navy', '000080'],
    ['Midnight Blue', '191970'],
    ['Cornsilk', 'FFF8DC'],
    ['Blanched Almond', 'FFEBCD'],
    ['Bisque', 'FFE4C4'],
    ['Navajo White', 'FFDEAD'],
    ['Wheat', 'F5DEB3'],
    ['Burly Wood', 'DEB887'],
    ['Tan', 'D2B48C'],
    ['Rosy Brown', 'BC8F8F'],
    ['Sandy Brown', 'F4A460'],
    ['Goldenrod', 'DAA520'],
    ['Dark Goldenrod', 'B8860B'],
    ['Peru', 'CD853F'],
    ['Chocolate', 'D2691E'],
    ['Saddle Brown', '8B4513'],
    ['Sienna', 'A0522D'],
    ['Brown', 'A52A2A'],
    ['Maroon', '800000'],
    ['White', 'FFFFFF'],
    ['Snow', 'FFFAFA'],
    ['Honeydew', 'F0FFF0'],
    ['Mint Cream', 'F5FFFA'],
    ['Azure', 'F0FFFF'],
    ['Alice Blue', 'F0F8FF'],
    ['Ghost White', 'F8F8FF'],
    ['White Smoke', 'F5F5F5'],
    ['Seashell', 'FFF5EE'],
    ['Beige', 'F5F5DC'],
    ['Old Lace', 'FDF5E6'],
    ['Floral White', 'FFFAF0'],
    ['Ivory', 'FFFFF0'],
    ['Antique White', 'FAEBD7'],
    ['Linen', 'FAF0E6'],
    ['Lavender Blush', 'FFF0F5'],
    ['Misty Rose', 'FFE4E1'],
    ['Gainsboro', 'DCDCDC'],
    ['Light Grey', 'D3D3D3'],
    ['Silver', 'C0C0C0'],
    ['Dark Gray', 'A9A9A9'],
    ['Gray', '808080'],
    ['Dim Gray', '696969'],
    ['Light Slate Gray', '778899'],
    ['Slate Gray', '708090'],
    ['Dark Slate Gray', '2F4F4F'],
    ['Black', '000000']
]
